### ISSUE TITLE
Foundling CtDs

### ISSUE THREAD

**Issue by RoxanneSHS** [BiGWorldProject/BiG-World-Fixpack#10]
I made this report http://www.shsforums.net/topic/58134-foundling-between-the-shades-beta-available/page-2#entry589964 on the mod forum a while back, Never any response.

The issue is an animation L#Fowall.bam in area L#Fou0.are.
Removing it from the are file solves the issue until a repair is made.
I have no idea however how to do this by the means of fixpack.

**Comment by agb1** [comment]
Thanks - should be resolved now.
