### ISSUE TITLE
Isra in EET

### ISSUE THREAD

**Issue by RoxanneSHS** [BiGWorldProject/BiG-World-Fixpack#11]
```
> Isra is provided in two parts to EET BGEE and BG2EE - when you install BOTH parts in an EET game, her PIDs are triggered wrong. This could be corrected by adding this
> 
> In **BGEE** mod Isra/dialogue/rh#israJ.d
> IF ~IsGabber(Player1)~ THEN BEGIN pid
> >>>>>> 
> IF ~IsGabber(Player1) GlobalLT("Chapter","Global".13)~ THEN BEGIN pid
> 
> In **BG2EE** mod Isra_bg2/dialogue/rh#isrJ.d
> IF ~IsGabber(Player1)~ THEN BEGIN pid
>  SAY @2596
> >>>>>>
> IF ~IsGabber(Player1) GlobalGT("Chapter","Global".13)~ THEN BEGIN pid
>  SAY @2596
> 
> In same dialogue however
> APPEND RH#ISRJ
> **This must remain unchanged**
> IF ~IsGabber(Player1) Global("Chapter","GLOBAL",%bg2_chapter_5%)~ THEN BEGIN UDpid
>  SAY @2593
> 
> And once again I have now idea about how fixpack could add this (& only if both mods are selected for EET install).
> 
> PS - This proposal does not cover chapter13 itself, as Isra is not joinable during this part.
```

**Comment by agb1** [comment]
Isra for BG1 is installed before EET so the join dialogue condition should be patched automatically with a GlobalLT("endofbg1","Global",2).

Isra for BG2 is installed after EET and needs a !GlobalLT("endofbg1","Global",2) added to the IsGabber condition.

Correct?

**Comment by RoxanneSHS** [comment]
In principle yes BUT stuff is different here as Isra is a mod NPC and NOT continuous in the EET sense,
EET adds her BG1 joined dialogue to the BG2 joined dialogue (according to its rules) Thus the IsGabber appears twice and due to the state priority inherited from the originals, the BG1 Pid triggers always. You do not recognise it until you are in BG2 part. 
Your solution is fine, as it covers the non-EET even non-EE games as well. I was narrowing it to EET only, so yours is better,

**Comment by agb1** [comment]
On closer inspection, I see that Isra in BG1 uses RH#IsrAj.dlg - but Isra in BG2 uses RH#isrj (no A).  EET is not joining these dialogue files; the BG1 Isra is somehow remaining with you until BG2.

EET adds code to Isra's BG1 override script (RH#ISRA) that would remove her from the game after chapter 7 (SoD), but that code has an exception if Isra is in your party during the SoD transition (so far, this seems correct).

EET also adds code to Isra's BG1 override script that would remove her from the game in chapter 14, and again this code does not trigger while she is in the party.  However, EET uses the script K#TELBGT during the SoD to BG2 transition, and that script forces all still-in-party NPCs to LeaveParty() and DestroySelf().  We need to investigate why that script did not remove the BG1 Isra from your game.

**Comment by RoxanneSHS** [comment]
>  EET is not joining these dialogue files; the BG1 Isra is somehow remaining with you until BG2.

Not exactly - I had Isra some time during BG1 but did not take her into SoD. I rejoined with the BG2 Isra as foreseen later on. Everything is correct, **the new Isra is THE BG2 Isra,** RH#Isra2 has her BG2 dialogue (without A). BUT - EET has joined the two files and RH#isrj (no A). has  RH#IsrAj.dlg  appended to it. 
This merging is the reason why both PID triggers (from BG1 and BG2) are present but because of State priority in the joined dialogue, the BG1-PID triggers in BG2.

PS - Except for the PID I have not found any other issue with the joined file, her BG2 contents is otherwise triggered correctly.

PPS - According to NI, the BG1 Isra is still in Nashkel Inn where I have left her during BG1. She correctly self-destroys by EET script when I revisit the BG1 area. (As does Neera whom I left there as well). So again, except for PID the rest looks fine.

**Comment by agb1** [comment]
I don't see the BG1 dialogue states in RH#IsrJ.DLG in my install.  I also don't see how EET could be merging them; the DV of Isra in BG1 is RH#ISRA but it is RH#ISRA2 (+2) in BG2.  They are entirely separate NPCs as far as EET is concerned.  Can you run a change-log on RH#IsrJ.DLG to see if something else modified it?

**Comment by RoxanneSHS** [comment]
```
Mods affecting RH#ISRJ.DLG:
00000: ~SANDRAHNPC/SETUP-SANDRAHNPC.TP2~ 0 12 // Mod Interactions: v2.03.b
00001: ~EET_END.TP2~ 0 0 // Finalise EET (last mod in install order)

Mods affecting RH#ISRAJ.DLG:
00000: ~SANDRAHNPC/SETUP-SANDRAHNPC.TP2~ 0 12 // Mod Interactions: v2.03.b
00001: ~EET_END.TP2~ 0 0 // Finalise EET (last mod in install order)

My own mod appends to it (it also does it to the other one in BG1)
EET_end, it would be the one to merge dialogues

I fully agree that EET should treat Isra as two completely separate NPCs, no idea where the match comes in.

Just for completeness - this is how Sandrah treats the two (independent mods)
ACTION_IF FILE_EXISTS_IN_GAME ~BRH#ISRA.dlg~ THEN BEGIN
COMPILE ~SandrahNPC/Mods/IsraSan.d~
EXTEND_TOP
~RH#Isra.bcs~ ~SandrahNPC/Mods/IsraSan.baf~
PRINT ~ Isra detected - Sandrah Relationship added~
END ELSE BEGIN
  PRINT ~Isra not detected - skipped ~
END

ACTION_IF FILE_EXISTS_IN_GAME ~BRH#ISR.dlg~ THEN BEGIN
COMPILE ~SandrahNPC/Mods/IsraSan2.d~
EXTEND_TOP
~RH#Isr.bcs~ ~SandrahNPC/Mods/IsraSan.baf~
PRINT ~ Isra BG2 detected - Sandrah Relationship added~
END ELSE BEGIN
  PRINT ~Isra BG2 not detected - skipped ~
END
```

**Comment by RoxanneSHS** [comment]
I checked one more thing that convinces me it is an EET_end bug
RH#Isrj in the EET/backup/end/0 has 1974 states
RH#isrj in override has 2496 states (and rh#israj has 569 states)
(the negative discrepancy comes from the fact that the additional Sandrah states appended to rh#israj are not appearing in the merged file, another strange thing). I have no idea whatsoever might have gone wrong with it all.

 I suggest to keep this issue pending as a local error and I will investigate it again on my next install.

**Comment by agb1** [comment]
As a side-note, I just checked all of Isra-in-BG1's files for "RH#ISRA2" and found a single match in BRH#ISRA banter dialogue, where one of the Kivan banters was incorrectly triggering only for RH#ISRA2.  So I have now created a new patch for Isra-in-BG1 due to your report, but it has nothing to do with your own reported issue.

**Comment by RoxanneSHS** [comment]
Fixpack patches available

**Comment by lynxlynxlynx** [comment]
Can the patches be dropped then?

Also, where's the new release: http://www.shsforums.net/files/category/118-isra/

**Comment by RoxanneSHS** [comment]
My comment was misleading - I just wanted to close the issue inside Fixpack. What Fixpack can do, has been done.
