### ISSUE TITLE
Don't apply patch for SCS v2.x compatibility on 1.3 (and original) installs

### ISSUE THREAD

**Issue by arjunphull** [BiGWorldProject/BiG-World-Fixpack#12]
Android and iOS are stuck at 1.3 at the moment and I'm sure a lot of people are still running the original games.

**Comment by agb1** [comment]
What part of the Fixpack-patched SCS code is failing when installed on pre-2.x EE?

**Comment by arjunphull** [comment]
The main SCS component fails to install. I forget what it is called but it is a dependency for almost all other components. Vanilla SCS v30 installs properly.

**Comment by agb1** [comment]
Can you provide the specific error from setup-stratagems.debug?

**Comment by arjunphull** [comment]
please see attached.

[SETUP-STRATAGEMS.DEBUG.txt](https://github.com/BiGWorldProject/BiG-World-Fixpack/files/642517/SETUP-STRATAGEMS.DEBUG.txt)

**Comment by agb1** [comment]
Thanks.  I see that you are also installing Spell Revisions, which means we are applying Kreso's Revised SCS patches too.  It is not obvious to me why the patches are causing this problem as we do not modify prebuff_bg1.2da that contains the offending "BLESS" entry.  Will investigate further.

**Comment by ALIENQuake** [comment]
BWFixpack can't support older version of games/mods. Sorry.
