### ISSUE TITLE
Tales of Anegh in EET

### ISSUE THREAD

**Issue by RoxanneSHS** [BiGWorldProject/BiG-World-Fixpack#14]
I made these reports in the mod's own repository. I do not know if this is maintained or if Fixpack should take care intermediately.

https://github.com/whiteagnus/ToA/issues/1#issue-197033859

**Comment by ALIENQuake** [comment]
whiteagnus retired from the internet so if anything, a fork or BWFixpack should take care about this.

**Comment by RoxanneSHS** [comment]
I added it to fixpack.
I have no idea if creating a fork finds someone to merge it?

**Comment by ALIENQuake** [comment]
Unless whiteagnus will be back (very unlikely) there will be no one to merge fork but crating fork will allow to add all patches directly to the mod ( use SUPPORT keyword instead of AUTHOR ) and make contributions from other people possible

**Comment by RoxanneSHS** [comment]
My corrections were not necessary. The real issue was just that the mod was using an outdated version of EET_functions.tph. to convert chapter references to EET (still was using a pre-SoD version).
I have no idea of how such a special case would be handled by creating a fork?
