### ISSUE TITLE
Backslashes in patch files should be replaced automatically with forward-slashes for Linux/macOS compatibility

### ISSUE THREAD

**Issue by Huesli** [BiGWorldProject/BiG-World-Fixpack#22]
Patch files using forward slashes, such as
`--- edwin/baf/edwin.baf	2014-12-29 08:13:25.000000000 -0500`
seem to work well on all operating systems.

However, patch files using backward slashes, such as
`--- haerdalisromance\haerdalisromance.tp2	Sun Nov 10 20:48:18 2013`
do not work on Linux/macOS, they result in error messages such as this:
```
Invalid filename: haerdalisromance\haerdalisromance.tp2

! patch -p0 -f --verbose --no-backup-if-mismatch --ignore-whitespace < 'BiG_World_Fixpack/haerdalisromance/haerdalisromance.tp2.patch' | tee -a '_ApplyPatches_verbose.log'
Hmm...  Looks like a unified diff to me...
(Stripping trailing CRs from patch.)
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- haerdalisromance\haerdalisromance.tp2	Sun Nov 10 20:48:18 2013
|+++ C:\BWP Patchstudio\patched files\haerdalisromance\haerdalisromance.tp2	Fri Jul 03 23:58:09 2015
--------------------------
No file to patch.  Skipping patch.
Hunk #1 ignored at 4.
1 out of 1 hunk ignored
done
```

Changing this to
`--- haerdalisromance/haerdalisromance.tp2	Sun Nov 10 20:48:18 2013`
will allow it to patch successfully.

For this reason I suggest to replace any backward slashes in patch file names automatically (in _ApplyPatches.tp2) before applying the patch.

**Comment by RoxanneSHS** [comment]
Fixed by Ineth2
