### ISSUE TITLE
Tactics component "Improved Ilych" conflicts with BGT-WeiDu 1.18?

### ISSUE THREAD

**Issue by Sebastian-c4** [BiGWorldProject/BiG-World-Fixpack#34]
Check the links in "_BWP fixes.txt" and got no answer.
Manually removed lines in Setup-Tactics.tp2.patch and installed that component with BGT-WeiDu 1.18 and find no error in game.

**Comment by RoxanneSHS** [comment]
Just for info 
The BWS contains also this limitation:
BGT conflicts with Tactics' Improved Ilyich=C:BGT(-):Tactics(0)

**Comment by Sebastian-c4** [comment]
I tested either
install mods manually,
or install with BWP install pack using edited individual.bat,
or install with BWS by ignore the conflict issue.
Ilych and other enemies shows and fight correctly.

**Comment by ALIENQuake** [comment]
There was a reason which such conflict was set, I'm not convinced that We should remove it just to see some reports about things not working in the upcoming months. Anyone can ignore conflict for their own needs.

**Comment by lynxlynxlynx** [comment]
The reason is not recorded in commit history or somewhere else?

**Comment by ALIENQuake** [comment]
@lynxlynxlynx Unfortunately not, conflict comes from old BWP or from some old forum report.
