### ISSUE TITLE
Add a mechanism for copying common tools (iconv.exe, oggdec.exe, ...) into mod folders

### ISSUE THREAD

**Issue by Ineth2** [BiGWorldProject/BiG-World-Fixpack#38]
### Background

Making mods compatible with both the classic games and the Enhanced Edition, and with all operating systems, tends to require certain programs to convert between different resource formats.

WeiDU provides the `HANDLE_*` action functions to automatically run those programs with the right parameters for any given game engine and operating system, but it doesn't include the actual program executables &ndash; every mod needs to bundle them.

The executables in question are:

* [`HANDLE_CHARSETS`](http://www.weidu.org/~thebigg/README-WeiDU.html#HANDLE_CHARSETS) needs `iconv.exe`+DLL's
* [`HANDLE_TILESETS`](http://www.weidu.org/~thebigg/README-WeiDU.html#HANDLE_TILESETS) needs `win32/tisunpack.exe`, `osx/tisunpack` and `unix/tisunpack`.
* [`HANDLE_AUDIO`](http://www.weidu.org/~thebigg/README-WeiDU.html#HANDLE_AUDIO) needs `oggdec.exe` and `sox`.

And there are even some more provided by third-party WeiDU libraries, e.g.:

* [`HANDLE_TILECONV`](https://github.com/Argent77/DjinniCompanion/blob/v2.5/DjinniCompanion/lib/a7_tools.tpa) *[by @Argent77]* needs `win32/tileconv.exe`, `osx/tileconv` and `unix/tileconv`.

Older mods that were created before the EE existed, don't bundle those executables &ndash; so the Fixpack needs to add them if it wants to fix and modernize those mods.

The Fixpack started doing this for some mods quite some time ago, at least for `HANDLE_CHARSETS`.  
At first the `_copy` mechanism was used, with a separate copy of the `iconv.exe` executable for each mod for which a `TP2` patch in the Fixpack added a `HANDLE_CHARSETS` call.
At some point @agb1 moved `iconv.exe` to a central location in the Fixpack and made the `TP2` patches of the individual mods refer to it (c.f. a8375588fdf48bcfd07985259d7b113abc7a05cb and bdf0a863bd1e302ea1ebfaaf239e7d5ee7c86937).
Now, @ALIENQuake [champions the return](https://github.com/BiGWorldProject/BiG-World-Fixpack/pull/37#discussion_r148935589) to using separate copies.

### The Problem

The problem is that neither of the two approaches is satisfactory...

Disadvantages of adding a copy of each executable to the `_copy` folder for each mod that needs it:
* The **download size** of the Fixpack will increase significantly.
* **Maintenance** is more difficult. Consider e.g. if a tool had a bug and a new version is released to fix it, or if it is decided to add or modify a copyright notice next to a tool executable, etc. &ndash; *all* copies will have to be updated individually. It will be easy for contributors to accidentally leave some copies out of sync and create a mess.

Disadvantage of having a central copy and referring to it directly in the `HANDLE_*` function calls added by `.tp2` patches:
* The resulting patched mods aren't **self-contained**, as their TP2 now refers to paths that only exist when the Fixpack is extracted. This makes it harder for mod authors to backport Fixpack patches to their mods.

### Proposed Solution

I'd suggest the following:

1) Store **a single copy of each tool** in the Fixpack, for example like this:  
```
BiG World Fixpack/_utils/iconv/iconv.exe
BiG World Fixpack/_utils/iconv/libiconv2.dll
BiG World Fixpack/_utils/iconv/libintl3.dll
BiG World Fixpack/_utils/iconv/libcharset1.dll
BiG World Fixpack/_utils/iconv/libcharset1.dll
BiG World Fixpack/_utils/tisunpack/win32/tisunpack.exe
BiG World Fixpack/_utils/tisunpack/osx/tisunpack
BiG World Fixpack/_utils/tisunpack/unix/tisunpack
BiG World Fixpack/_utils/oggdec/oggdec.exe
BiG World Fixpack/_utils/sox/sox
```

2) Add **a `_copy_util` mechanism** to the Fixpack installer, to complement the existing `_copy`:

  `_copy_util` would be a file that can be added to each mod's patch folder, and contain one line per tool that should be added to the mod.  
Each line would consist of the tool name, followed by a TAB, followed by the path (relative to the target mod folder) to which it should be copied.  
For example:
```
iconv	tra\iconv
oggdec	audio
sox	audio
```
This example would create the following files inside the target mod folder:
```
tra/iconv/iconv.exe
tra/iconv/libiconv2.dll
tra/iconv/libintl3.dll
tra/iconv/libcharset1.dll
tra/iconv/libcharset1.dll
audio/oggdec.exe
audio/sox
```

**Comment by lynxlynxlynx** [comment]
"iconv	tra\iconv" <-- this would only work on windows. And people would keep screwing up the tabs, so other delimiters are better.

But I don't see how this would fix the selfsufficiency problem. You'd still need the whole fixpack present for this to work.

**Comment by Ineth2** [comment]
@lynxlynxlynx I basically just complied with the existing conventions there.

> "iconv tra\iconv" <-- this would only work on windows.

It would work on any operating system that the Fixpack installer implementation *makes* it work on... :)

The existing patching mechanisms (`_copy`, `_delete`, `_rename` etc.) currently use backslash-paths for many mods as well, and I've made that work on Linux and Mac [with a recent commit](https://github.com/BiGWorldProject/BiG-World-Fixpack/commit/c0a33cbb1a4582f5a2f77e271b30bcbd444685b1).

> And people would keep screwing up the tabs, so other delimiters are better.

Among the current patching mechanisms, `_rename` is the only one that uses two fields per line, and it uses a TAB as delimiter &ndash; see the documentation at the top of [_ApplyPatches.tp2](https://github.com/BiGWorldProject/BiG-World-Fixpack/blob/master/_ApplyPatches.tp2).  
I assume TAB was chosen because, unlike SPACE, you can be reasonably sure that it doesn't appear in file & folder names &ndash; and it makes the fields easy to parse in WeiDU code using [`READ_2DA_ENTRY`](http://www.weidu.org/~thebigg/README-WeiDU.html#READ_2DA_ENTRY).

> You'd still need the whole fixpack present for this to work.

You'd still need the Fixpack to apply the Fixpack, sure.

But once it's been applied to a mod, those patched mod files would be self-sufficient &ndash; the mod author could zip them up and release them as the new version of the mod with no dependency on the Fixpack.

**Comment by lynxlynxlynx** [comment]
weidu/engines don't care about whitespace type, all create new columns when reading 2das.

for the selfsufficiency I meant that now you can install the fixes to a mod just by patching, using a subset (granted, git isn't as good as svn here). This would change, particularly if we started hardcoding tool paths.

**Comment by Ineth2** [comment]
@lynxlynxlynx 
> I meant that now you can install the fixes to a mod just by patching, using a subset

I don't follow.

Right now, installing fixes doesn't just involve the contents of
```
BiG World Fixpack/%MOD_FOLDER%/
```
but also a whole bunch of shared Fixpack files:
```
_ApplyPatches.tp2
BiG World Fixpack/_utils/patch.exe
BiG World Fixpack/_utils/find.exe
BiG World Fixpack/_utils/tee.exe
BiG World Fixpack/_utils/trans_crlf.sh
...
```

So mod patches really aren't self-contained, nor do I see any point in trying to make them so.  
It's completely reasonable that to install the Fixpack, you need the whole Fixpack.  
The proposal in this ticket wouldn't change anything in that regard.

The  only self-sufficiency that makes sense to aim for, IMO, is that of the resulting patched mods.  
*That's* the reason why @ALIENQuake (if I understood him correctly) doesn't want to let TP2 patches refer to an `iconv.exe` outside of the mod folder, and this is what my proposal addresses.

**Comment by ALIENQuake** [comment]
I'm all for implementing such functionality, call it "_include" to the fact that we are coping something from one main directory into every mod directory. But not every mod have tp2 code which points to:
tra/iconv ...
audio/...
so this is only for new patches and old patches would need to be adapted?

**Comment by Ineth2** [comment]
> call it "_include"

You're right, that *does* sound better.

> But not every mod have tp2 code which points to [...]

Every mod's patch folder would have its own `_include` file, to specify the correct paths for that mod. `tra/iconv` and `audio` were just used as an example.
(Only for mods that need it, of course - not all mods require binaries to be added by the Fixpack.)

**Comment by ALIENQuake** [comment]
@Ineth2 Sounds good. Unfortunately agb1 went offline, will you be able to implement such feature using weidu code?

**Comment by Ineth2** [comment]
I think so. Not this weekend though.

**Comment by ALIENQuake** [comment]
@Ineth2 No problem, take you time.

**Comment by ALIENQuake** [comment]
@Ineth2 Any progress?
