### ISSUE TITLE
Valerie in EET

### ISSUE THREAD

**Issue by RoxanneSHS** [BiGWorldProject/BiG-World-Fixpack#8]
I have no idea of how I can commit the following to fixpack directly. So I do it here and maybe someone can explain how to do it.

Only IF the game is EET
and

```
ACTION_IF FILE_EXISTS_IN_GAME ~T2Val.cre~ THEN BEGIN
EXTEND_TOP ~BD0103.bcs~ ~Valeriegone.baf~
END
```

where Valeriegone.baf is this

```
IF
	OR(2)
		InMyArea("T2Val")
		InPartyAllowDead("T2Val")
	GlobalLT("BD_PLOT","GLOBAL",51)
THEN
	RESPONSE #100
		ActionOverride("T2Val",LeaveParty())
		SmallWait(1)
		ActionOverride("T2Val",DestroySelf())
		Continue()
END
```

-----This is to solve http://gibberlings3.net/forums/index.php?showtopic=27741&page=28#entry248276

> There is an issue with Valerie NPC and EET compatibility:
>  
> At BG1 end she transits into SoD when in party and she stays in the party after you leave Koslaz dungeon, This by itself is completely legitimate (my own NPC does the same), but in Valerie's case tis seems to be an error - she has no SoD contents and still *thinks* she is in BG1, having interactions to the pre-Sarevok plot etc.
> I call it a bug because there was a similar issue with her in BGT, where she followed the transition into Irenicus dungeon after BG1 although her BG2 contents did not exist,
> Her EET compatibility might have been determined on basis of the earlier version without SoD?

**Comment by ALIENQuake** [comment]
@RoxanneSHS Ok but why some lines are marked as <---deleted--->?

Anything in between tildes seem to appear as deleted?? It is this editor, if I open it in writing mode it appears normal.

**Comment by ALIENQuake** [comment]
@RoxanneSHS Please answer to comments, don't edit them :P
Indeed it's the github markdown/editor, please use 'code' to post weidu code next time :+1:

**Comment by RoxanneSHS** [comment]
Thanks for the help. 
Looking at how (I think) fixpack works, I understand that it would add a block to the mod's tp2 and add files into the mod folder, all of that prior to the mod's installation. 
If this is correct, then in the present case it would mean that: 
1. This is to be added to **Valerie.tp2**
`ACTION_IF FILE_EXISTS_IN_GAME ~bd0103.are~ THEN BEGIN

EXTEND_TOP ~BD0103.bcs~ ~Valerie/scripts/Valeriegone.baf~

END` 
2. Valeriegone.baf with the content outlined above is to be copied into the **valerie/scripts folder**

**Comment by ALIENQuake** [comment]
@RoxanneSHS If the new tp2 code should be only executed for EET, shouldn't it be like:

```
ACTION_IF ( GAME_IS EET AND FILE_EXISTS_IN_GAME ~bd0103.are~ ) THEN BEGIN

EXTEND_TOP ~BD0103.bcs~ ~Valerie/scripts/Valeriegone.baf~

END
```

?

**Comment by RoxanneSHS** [comment]
After consideration I think that it would also apply for BGEE with SoD, this is why I propose to have the check for the area instead (it is SoD). In EET, Valerie is installed during the BGEE part, thus EET would import the corrected version already?

**Comment by ALIENQuake** [comment]
@RoxanneSHS Yes, if the code for BG:EE+SoD will be correct, EET will import it. The code fixes SoD issue, not directly EET so code should check SoD or EET (for someone who don't use EET)

**Comment by agb1** [comment]
Wouldn't it be better to suppress her inappropriate dialogues in SoD with GlobalLT("EndOfBG1","GLOBAL",1) [which is set to 1 after Sarevok's death] instead of deleting her in SoD?

Maybe she has items the party wants to keep, or the party relies on her magic for combat, or...

**Comment by RoxanneSHS** [comment]
My point is that the Valerie mod has not been updated ever since SoD appeared. The author did not foresee the addon and thus has taken no action for this case. She and Sandrah are the only ones currently who stay with the PC through this transition - while Sandrah does this as part of her story in SoD, Valeries's transition plainly is an apparent oversight. (It is like someone stays in the party during old BGT transition into Sarevok's dungeon, you immediately recognise that this was not intended - then the wrong dialogues confirm this on top.)
Anyway, correcting her dialogues would be better than nothing.

**Comment by agb1** [comment]
I've implemented the simpler option as suggested - BD0103.BCS will be patched to remove Valerie.
