### ISSUE TITLE
Firkrag in EET

### ISSUE THREAD

**Issue by RoxanneSHS** [BiGWorldProject/BiG-World-Fixpack#9]
This issue 
http://gibberlings3.net/forums/index.php?showtopic=28161&page=46#entry248481

Proposal
EXTEND_BOTTOM Firkra01.bcs with this

IF
GlobalGT("DomainPaladinBattle","GLOBAL",0)
AreaCheck("ar0406")
THEN
RESPONSE #100
DestroySelf()
END

If my research is correct, this applies as well to BGT, although the Ajantis mod contains a fix via ar0406.bcs (only if you have that mod installed).

**Comment by agb1** [comment]
Where to put this, is the question.  It's ultimately a bug that Beamdog should fix, but until then... EET has its own fixpack, but we also want to fix it for regular BG2EE.  I'm thinking this belongs in Nightfarer's Cre Patcher.

**Comment by RoxanneSHS** [comment]
Probably bean dogs would not see it as a bug - after all it is the original BG2 code. It is an oversight that was always in the game but you only notice it if you visit the Copper Coronet during the Firkrag campaign. Not many may do that.

**Comment by agb1** [comment]
This issue has been addressed in Nightfarer's Area Patcher v16, new component 2003.  The Area Patcher is packaged with the BiG World Fixpack but it is not installed by the Fixpack script.

BWP and BWS include separate code to copy the Area_Patcher folder to the game folder and install it.
